### ISSUE TITLE
Skill not working without GUI

### ISSUE THREAD

**Issue by Dante1975X** [OpenVoiceOS/ovos-skill-iss-location#18]
The skill is actually not working when runing ovos headless without GUI

There is always an error when the skill is trying to create the map image.
```

2024-11-10 11:43:01.015 - skills - ovos_core.transformers:transform:64 - DEBUG - ovos-utterance-cancel: {}

2024-11-10 11:43:01.016 - skills - ovos_core.transformers:transform:64 - DEBUG - ovos-utterance-normalizer: {'client_name': 'mycroft_cli', 'source': 'debug_cli', 'destination': ['skills'], 'lang': 'en-us'}

2024-11-10 11:43:01.018 - skills - ovos_core.transformers:transform:64 - DEBUG - ovos-utterance-corrections: {'client_name': 'mycroft_cli', 'source': 'debug_cli', 'destination': ['skills'], 'lang': 'en-us'}

2024-11-10 11:43:01.021 - skills - ovos_core.intent_services:get_pipeline:241 - DEBUG - Session pipeline: ['stop_high', 'converse', 'ocp_high', 'padatious_high', 'adapt_high', 'ocp_medium', 'fallback_high', 'stop_medium', 'adapt_medium', 'padatious_medium', 'adapt_low', 'common_qa', 'fallback_medium', 'fallback_low']

2024-11-10 11:43:01.021 - skills - ovos_core.intent_services:handle_utterance:382 - DEBUG - no match from <bound method StopService.match_stop_high of <ovos_core.intent_services.stop_service.StopService object at 0x7be58ee82fc0>>

2024-11-10 11:43:01.068 - skills - ovos_core.intent_services:handle_utterance:382 - DEBUG - no match from <bound method ConverseService.converse_with_skills of <ovos_core.intent_services.converse_service.ConverseService object at 0x7be5b1f302c0>>

2024-11-10 11:43:01.220 - skills - padacioso:calc_intent:240 - INFO - No match

2024-11-10 11:43:01.220 - skills - ovos_core.intent_services:handle_utterance:382 - DEBUG - no match from <bound method OCPPipelineMatcher.match_high of <ovos_core.intent_services.ocp_service.OCPPipelineMatcher object at 0x7be58e0eab40>>

2024-11-10 11:43:01.221 - skills - ovos_core.intent_services.padatious_service:_match_level:48 - DEBUG - Padatious Matching confidence > 0.95

2024-11-10 11:43:01.224 - skills - ovos_core.intent_services:handle_utterance:370 - INFO - padatious_high match: IntentMatch(intent_service='Padatious', intent_type='ovos-skill-iss-location.openvoiceos:when_iss.intent', intent_data={}, skill_id='ovos-skill-iss-location.openvoiceos', utterance='when is the iss going to be over me')

2024-11-10 11:43:01.226 - skills - ovos_core.intent_services:handle_utterance:388 - DEBUG - intent matching took: 0.20508575439453125

2024-11-10 11:43:01.245 - skills - ovos_workshop.skills.mycroft_skill:settings:193 - WARNING - with MycroftSkill self.settings may not respect self.skill_id, path: /home/ovos/.config/mycroft/skills/skill-openhab/settings.json

2024-11-10 11:43:01.250 - skills - ovos_bus_client.client.client:on_default_session_update:166 - DEBUG - synced default_session

2024-11-10 11:43:02.537 - skills - ovos_bus_client.client.client:on_default_session_update:166 - DEBUG - synced default_session

Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers).

2024-11-10 11:43:04.663 - skills - ovos_utils.file_utils:resolve_resource_file:194 - WARNING - Deprecation version=0.1.0. Caller=ovos_utils.dialog:166. Expected a dict config and got None.

2024-11-10 11:43:04.673 - ovos-skill-iss-location.openvoiceos - ERROR - [Errno 2] No such file or directory: 'iss3.png'

Traceback (most recent call last):

  File "/home/ovos/.venv/lib/python3.12/site-packages/ovos_utils/events.py", line 78, in wrapper

    handler(message)

  File "/home/ovos/.venv/lib/python3.12/site-packages/ovos_skill_iss_location/__init__.py", line 176, in handle_when

    image = self.generate_map(lat, lon)

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ovos/.venv/lib/python3.12/site-packages/ovos_skill_iss_location/__init__.py", line 118, in generate_map

    iss = plt.imread(self.settings["iss_icon"])

          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ovos/.venv/lib/python3.12/site-packages/matplotlib/pyplot.py", line 2404, in imread

    return matplotlib.image.imread(fname, format)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/ovos/.venv/lib/python3.12/site-packages/matplotlib/image.py", line 1525, in imread

    with img_open(fname) as image:

         ^^^^^^^^^^^^^^^

  File "/home/ovos/.venv/lib/python3.12/site-packages/PIL/ImageFile.py", line 132, in __init__

    self.fp = open(fp, "rb")

              ^^^^^^^^^^^^^^

FileNotFoundError: [Errno 2] No such file or directory: 'iss3.png'
```

**Comment by Dante1975X** [comment]
With the latest update. The iss skill is now working for me without gui. Thx.
