### ISSUE TITLE
No such file or directory: '/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/ovos_skill_iss_location/iss3.png

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-skill-iss-location#4]
```
o 2] No such file or directory: '/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/ovos_skill_iss_location/iss3.png'
May 29 14:51:52 mark2 ovos-core[4880]: Traceback (most recent call last):
May 29 14:51:52 mark2 ovos-core[4880]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/ovos_skill_iss_location/__init__.py", line 76, in update_picture
May 29 14:51:52 mark2 ovos-core[4880]:     image = self.generate_map(lat, lon)
May 29 14:51:52 mark2 ovos-core[4880]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 29 14:51:52 mark2 ovos-core[4880]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/ovos_skill_iss_location/__init__.py", line 117, in generate_map
May 29 14:51:52 mark2 ovos-core[4880]:     iss = plt.imread(icon)
May 29 14:51:52 mark2 ovos-core[4880]:           ^^^^^^^^^^^^^^^^
May 29 14:51:52 mark2 ovos-core[4880]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/matplotlib/pyplot.py", line 2404, in imread
May 29 14:51:52 mark2 ovos-core[4880]:     return matplotlib.image.imread(fname, format)
May 29 14:51:52 mark2 ovos-core[4880]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 29 14:51:52 mark2 ovos-core[4880]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/matplotlib/image.py", line 1525, in imread
May 29 14:51:52 mark2 ovos-core[4880]:     with img_open(fname) as image:
May 29 14:51:52 mark2 ovos-core[4880]:          ^^^^^^^^^^^^^^^
May 29 14:51:52 mark2 ovos-core[4880]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/PIL/ImageFile.py", line 125, in __init__
May 29 14:51:52 mark2 ovos-core[4880]:     self.fp = open(fp, "rb")
May 29 14:51:52 mark2 ovos-core[4880]:               ^^^^^^^^^^^^^^
May 29 14:51:52 mark2 ovos-core[4880]: FileNotFoundError: [Errno 2] No such file or directory: '/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/ovos_skill_iss_location/iss3.png'
May 29 14:51:52 mark2 ovos-core[4880]: 2024-05-29 14:51:52.828 - skills - ovos_utils.file_utils:resolve_resource_file:163 - WARNING - Deprecation version=0.1.0. Caller=ovos_utils.dialog:166. Expected a dict config and got None.
May 29 14:51:52 mark2 ovos-core[4880]: 2024-05-29 14:51:52.854 - ovos-skill-iss-location.openvoiceos - ERROR - 'astronauts'
May 29 14:51:52 mark2 ovos-core[4880]: Traceback (most recent call last):
May 29 14:51:52 mark2 ovos-core[4880]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/ovos_utils/events.py", line 78, in wrapper
May 29 14:51:52 mark2 ovos-core[4880]:     handler(message)
May 29 14:51:52 mark2 ovos-core[4880]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/ovos_skill_iss_location/__init__.py", line 194, in handle_who
May 29 14:51:52 mark2 ovos-core[4880]:     p["name"] for p in self.gui["astronauts"]
May 29 14:51:52 mark2 ovos-core[4880]:                        ~~~~~~~~^^^^^^^^^^^^^^
May 29 14:51:52 mark2 ovos-core[4880]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/ovos_bus_client/apis/gui.py", line 303, in __getitem__
May 29 14:51:52 mark2 ovos-core[4880]:     return self.__session_data[key]
May 29 14:51:52 mark2 ovos-core[4880]:            ~~~~~~~~~~~~~~~~~~~^^^^^
May 29 14:51:52 mark2 ovos-core[4880]: KeyError: 'astronauts'
```

**Comment by goldyfruit** [comment]
Issue still there.

```
May 29 18:06:02 mark2 ovos-core[5975]: Traceback (most recent call last):
May 29 18:06:02 mark2 ovos-core[5975]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/ovos_skill_iss_location/__init__.py", line 79, in update_picture
May 29 18:06:02 mark2 ovos-core[5975]:     image = self.generate_map(lat, lon)
May 29 18:06:02 mark2 ovos-core[5975]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 29 18:06:02 mark2 ovos-core[5975]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/ovos_skill_iss_location/__init__.py", line 118, in generate_map
May 29 18:06:02 mark2 ovos-core[5975]:     iss = plt.imread(self.settings["iss_icon"])
May 29 18:06:02 mark2 ovos-core[5975]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 29 18:06:02 mark2 ovos-core[5975]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/matplotlib/pyplot.py", line 2404, in imread
May 29 18:06:02 mark2 ovos-core[5975]:     return matplotlib.image.imread(fname, format)
May 29 18:06:02 mark2 ovos-core[5975]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 29 18:06:02 mark2 ovos-core[5975]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/matplotlib/image.py", line 1525, in imread
May 29 18:06:02 mark2 ovos-core[5975]:     with img_open(fname) as image:
May 29 18:06:02 mark2 ovos-core[5975]:          ^^^^^^^^^^^^^^^
May 29 18:06:02 mark2 ovos-core[5975]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/PIL/ImageFile.py", line 125, in __init__
May 29 18:06:02 mark2 ovos-core[5975]:     self.fp = open(fp, "rb")
May 29 18:06:02 mark2 ovos-core[5975]:               ^^^^^^^^^^^^^^
May 29 18:06:02 mark2 ovos-core[5975]: FileNotFoundError: [Errno 2] No such file or directory: 'iss3.png'
May 29 18:06:02 mark2 ovos-core[5975]: 2024-05-29 18:06:02.926 - skills - ovos_utils.file_utils:resolve_resource_file:163 - WARNING - Deprecation version=0.1.0. Caller=ovos_utils.dialog:166. Expected a dict config and got None.
May 29 18:06:02 mark2 ovos-core[5975]: 2024-05-29 18:06:02.952 - ovos-skill-iss-location.openvoiceos - ERROR - 'astronauts'
May 29 18:06:02 mark2 ovos-core[5975]: Traceback (most recent call last):
May 29 18:06:02 mark2 ovos-core[5975]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/ovos_utils/events.py", line 78, in wrapper
May 29 18:06:02 mark2 ovos-core[5975]:     handler(message)
May 29 18:06:02 mark2 ovos-core[5975]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/ovos_skill_iss_location/__init__.py", line 195, in handle_who
May 29 18:06:02 mark2 ovos-core[5975]:     p["name"] for p in self.gui["astronauts"]
May 29 18:06:02 mark2 ovos-core[5975]:                        ~~~~~~~~^^^^^^^^^^^^^^
May 29 18:06:02 mark2 ovos-core[5975]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/ovos_bus_client/apis/gui.py", line 303, in __getitem__
May 29 18:06:02 mark2 ovos-core[5975]:     return self.__session_data[key]
May 29 18:06:02 mark2 ovos-core[5975]:            ~~~~~~~~~~~~~~~~~~~^^^^^
May 29 18:06:02 mark2 ovos-core[5975]: KeyError: 'astronauts'
```
