### ISSUE TITLE
ERROR - [Errno 2] No such file or directory: 'iss3.png'

### ISSUE THREAD

**Issue by goldyfruit** [OpenVoiceOS/ovos-skill-iss-location#5]
```
May 29 18:11:30 mark2 ovos-core[6110]: 2024-05-29 18:11:30.838 - ovos-skill-iss-location.openvoiceos - ERROR - [Errno 2] No such file or directory: 'iss3.png'
May 29 18:11:30 mark2 ovos-core[6110]: Traceback (most recent call last):
May 29 18:11:30 mark2 ovos-core[6110]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/ovos_skill_iss_location/__init__.py", line 79, in update_picture
May 29 18:11:30 mark2 ovos-core[6110]:     image = self.generate_map(lat, lon)
May 29 18:11:30 mark2 ovos-core[6110]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 29 18:11:30 mark2 ovos-core[6110]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/ovos_skill_iss_location/__init__.py", line 118, in generate_map
May 29 18:11:30 mark2 ovos-core[6110]:     iss = plt.imread(self.settings["iss_icon"])
May 29 18:11:30 mark2 ovos-core[6110]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 29 18:11:30 mark2 ovos-core[6110]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/matplotlib/pyplot.py", line 2404, in imread
May 29 18:11:30 mark2 ovos-core[6110]:     return matplotlib.image.imread(fname, format)
May 29 18:11:30 mark2 ovos-core[6110]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
May 29 18:11:30 mark2 ovos-core[6110]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/matplotlib/image.py", line 1525, in imread
May 29 18:11:30 mark2 ovos-core[6110]:     with img_open(fname) as image:
May 29 18:11:30 mark2 ovos-core[6110]:          ^^^^^^^^^^^^^^^
May 29 18:11:30 mark2 ovos-core[6110]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/PIL/ImageFile.py", line 125, in __init__
May 29 18:11:30 mark2 ovos-core[6110]:     self.fp = open(fp, "rb")
May 29 18:11:30 mark2 ovos-core[6110]:               ^^^^^^^^^^^^^^
May 29 18:11:30 mark2 ovos-core[6110]: FileNotFoundError: [Errno 2] No such file or directory: 'iss3.png'
May 29 18:11:30 mark2 ovos-core[6110]: 2024-05-29 18:11:30.900 - skills - ovos_utils.file_utils:resolve_resource_file:163 - WARNING - Deprecation version=0.1.0. Caller=ovos_utils.dialog:166. Expected a dict config and got None.
May 29 18:11:30 mark2 ovos-core[6110]: 2024-05-29 18:11:30.934 - ovos-skill-iss-location.openvoiceos - ERROR - 'imgLink'
May 29 18:11:30 mark2 ovos-core[6110]: Traceback (most recent call last):
May 29 18:11:30 mark2 ovos-core[6110]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/ovos_utils/events.py", line 78, in wrapper
May 29 18:11:30 mark2 ovos-core[6110]:     handler(message)
May 29 18:11:30 mark2 ovos-core[6110]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/ovos_skill_iss_location/__init__.py", line 146, in handle_iss
May 29 18:11:30 mark2 ovos-core[6110]:     self.gui.show_image(self.gui['imgLink'],
May 29 18:11:30 mark2 ovos-core[6110]:                         ~~~~~~~~^^^^^^^^^^^
May 29 18:11:30 mark2 ovos-core[6110]:   File "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/ovos_bus_client/apis/gui.py", line 303, in __getitem__
May 29 18:11:30 mark2 ovos-core[6110]:     return self.__session_data[key]
May 29 18:11:30 mark2 ovos-core[6110]:            ~~~~~~~~~~~~~~~~~~~^^^^^
May 29 18:11:30 mark2 ovos-core[6110]: KeyError: 'imgLink'
```

**Comment by JarbasAl** [comment]
do you have some old skill settings.json lying around? 

you can change the icon in the settings.json , i think your got the old path saved and thats why it's failing

**Comment by goldyfruit** [comment]
```json
{
    "__mycroft_skill_firstrun": false,
    "geonames_user": "jarbas",
    "map_style": "ortho",
    "center_iss": true,
    "center_location": false,
    "iss_size": 0.5,
    "iss_icon": "iss3.png",
    "dpi": 500,
    "astronauts": [
        {
            "name": "Jasmin Moghbeli",
            "craft": "ISS"
        },
        {
            "name": "Andreas Mogensen",
            "craft": "ISS"
        },
        {
            "name": "Satoshi Furukawa",
            "craft": "ISS"
        },
        {
            "name": "Konstantin Borisov",
            "craft": "ISS"
        },
        {
            "name": "Oleg Kononenko",
            "craft": "ISS"
        },
        {
            "name": "Nikolai Chub",
            "craft": "ISS"
        },
        {
            "name": "Loral O'Hara",
            "craft": "ISS"
        }
    ],
    "toponym": "The South Pacific Ocean",
    "iss_bg": "/home/goldyfruit/.venvs/ovos/lib/python3.12/site-packages/ovos_skill_iss_location/ui/iss.png"
}
```

**Comment by JarbasAl** [comment]
can you delete that please and try again?

"iss_icon" is the one causing trouble here

**Comment by goldyfruit** [comment]
Same with deleting the file.

**Comment by JarbasAl** [comment]
if the error log didnt change you are not on latest code

see default file path here https://github.com/OpenVoiceOS/ovos-skill-iss-location/blob/dev/__init__.py#L35

**Comment by goldyfruit** [comment]
Indeed.
